Modeling in Calculus: Early and Often
======================================
Materials from a 2012 MMA PREP Workshop
------------------

```{r, echo=FALSE}
displayFile <- function(path, text=path, type=c('html','Rmd')) {
  result <- paste(text, paste("[[", type, "] ](", path, ".", type, ")", sep="", collapse="" ) )
  return(result)
  }
```

This is where we will post materials from our 2012 MAA PREP Workshop.  Stay tuned.

### Monday

Text
### Tuesday


 * `r I(displayFile("Topic/Tides/tides-hawaii", "Tides in Hawaii"))`
 * `r I(displayFile("Topic/Optimization/Dog-Calculus", "Dog Calculus is Economics"))`
 
### Wednesday


<!-- ### Files by topic -->
```{r, results='asis', echo=FALSE, eval=FALSE}
directories <- dir('Topics')
files <- c()
for (d in directories){
  cat(paste('\n####', d, "\n"))
  files <- dir(paste('Topics/',d, sep=""))
  for (f in files) {
    if (grepl('.html', f) ) {
      cat(paste(' * [',d, "/", f,']', sep=""))
      cat(paste('(',d, "/", f,')\n', sep=""))
      }
  }
}
```