PREP 2012 Pre-Workshop Survey
========================================================
Three-quarters of the participants filled in the pre-workshop survey. 

```{r label="readdata",echo=FALSE}
s <- read.csv("~/Downloads/PREP2012-pre.csv")
```

Which courses are you interested in teaching in a modeling-based way?
<pre>
Beginning Algebra         1/15
Pre-calculus and Algebra  1/15
Business Calc             1/15
Calc I                   14/15
Calc II                  13/15
Calc III                  9/15
Linear Algebra            3/15
Differential Equations    7/15
Prob. Stats               4/15
Mathematical Modeling     1/15
</pre>

Software experience:
<pre>
            Never    Tried     Infrequent      Regularly    Expert
Sage:        10        2           3
R:           11                    1              1           1
MATLAB        6        5           2              2
Mathematica:  1        3           5              5           1
Maple:        3        2           4              5           1
</pre>

Teaching with Software:
<pre>
             Abs. Not.   Not Likely   Possible   Very Attractive  Already Use
Sage:            1           4           6            4
R:                           5           6            1               3
MATLAB:          2           5           6            1               1
Mathematica:     1           5           1            3               5
Maple:           2           5           3            3               2
</pre>

Eight of 15 participants report that they already use one of the listed software packages in their teaching.

Of the 6 people who already use either Mathematica or Maple,
<pre>
             Abs. Not  Not Likely   Possible     Very Attractive       Already Use
Sage:                                 4                 2
R:                           3        2                                    1
MATLAB:         1            1        3                                    1
</pre>

Authoring Software:
* 10 of 15 people use Latex either regularly or can help others learn.

Communications:
Not surprisingly, everyone is either comfortable or very comfortable with email. There's less comfort with other tools, but everyone is interested in several of these: Google Docs, Dropbox, blogs, wikis, or Moodle.

Obstacles to Teaching Modeling-Based Calculus:
<pre>
                              Huge    Significant    Little   None
Textbook                                    8            4       2
Software
  Student Skills                 1          5            5       2
  Faculty Skills                 1          4            8       1
Examples                         3          7            4       
Cramped Syllabus                 5          5            4       
Colleagues                       2          1            5       5
Prep time                        1          6            6       1
Connections                      2          3            8       1
Need to teach symbolics          3          3            7       1
</pre>

To what extent should modeling shape the topics in calculus?
<pre>
Not at all    a little   moderate   a lot   very much
    3            1           8        1        2
</pre>

Teach a whole course based on modeling?
<pre>
Not at all    a little   moderate   a lot   very much
    5             5         3                  3
</pre>
